// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: phtml/v1/options.proto

package phtmlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source of a request parameter.
type Source int32

const (
	// when the source is not specified
	Source_SOURCE_UNSPECIFIED Source = 0
	// source is the url path
	Source_SOURCE_PATH Source = 1
	// source is the url path
	Source_SOURCE_QUERY Source = 2
	// is the the body with form encoding
	Source_SOURCE_FORM Source = 3
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_PATH",
		2: "SOURCE_QUERY",
		3: "SOURCE_FORM",
	}
	Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"SOURCE_PATH":        1,
		"SOURCE_QUERY":       2,
		"SOURCE_FORM":        3,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_phtml_v1_options_proto_enumTypes[0].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_phtml_v1_options_proto_enumTypes[0]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Source) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Source(num)
	return nil
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_phtml_v1_options_proto_rawDescGZIP(), []int{0}
}

// options for defining a route.
type TemplOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the component constructor function.
	Component *string `protobuf:"bytes,1,opt,name=component" json:"component,omitempty"`
}

func (x *TemplOptions) Reset() {
	*x = TemplOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phtml_v1_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplOptions) ProtoMessage() {}

func (x *TemplOptions) ProtoReflect() protoreflect.Message {
	mi := &file_phtml_v1_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplOptions.ProtoReflect.Descriptor instead.
func (*TemplOptions) Descriptor() ([]byte, []int) {
	return file_phtml_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *TemplOptions) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

// options for defining a route.
type RouteOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// pattern for go 1.22 router.
	Pattern *string `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
}

func (x *RouteOptions) Reset() {
	*x = RouteOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phtml_v1_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOptions) ProtoMessage() {}

func (x *RouteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_phtml_v1_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOptions.ProtoReflect.Descriptor instead.
func (*RouteOptions) Descriptor() ([]byte, []int) {
	return file_phtml_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *RouteOptions) GetPattern() string {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return ""
}

// options for configuring parsing a request.
type ParamFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// in determines the source of the paramter.
	Source *Source `protobuf:"varint,1,opt,name=source,enum=phtml.v1.Source" json:"source,omitempty"`
}

func (x *ParamFieldOptions) Reset() {
	*x = ParamFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phtml_v1_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamFieldOptions) ProtoMessage() {}

func (x *ParamFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_phtml_v1_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamFieldOptions.ProtoReflect.Descriptor instead.
func (*ParamFieldOptions) Descriptor() ([]byte, []int) {
	return file_phtml_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *ParamFieldOptions) GetSource() Source {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

var file_phtml_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*ParamFieldOptions)(nil),
		Field:         1198,
		Name:          "phtml.v1.param",
		Tag:           "bytes,1198,opt,name=param",
		Filename:      "phtml/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TemplOptions)(nil),
		Field:         1197,
		Name:          "phtml.v1.templ",
		Tag:           "bytes,1197,opt,name=templ",
		Filename:      "phtml/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RouteOptions)(nil),
		Field:         1199,
		Name:          "phtml.v1.route",
		Tag:           "bytes,1199,opt,name=route",
		Filename:      "phtml/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional phtml.v1.ParamFieldOptions param = 1198;
	E_Param = &file_phtml_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional phtml.v1.TemplOptions templ = 1197;
	E_Templ = &file_phtml_v1_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional phtml.v1.RouteOptions route = 1199;
	E_Route = &file_phtml_v1_options_proto_extTypes[2]
)

var File_phtml_v1_options_proto protoreflect.FileDescriptor

var file_phtml_v1_options_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x2e,
	0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x22, 0x3d, 0x0a, 0x11,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2a, 0x54, 0x0a, 0x06, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x50, 0x41, 0x54, 0x48, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x10,
	0x03, 0x3a, 0x51, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xae, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x3a, 0x4e, 0x0a, 0x05, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x12, 0x1f, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xad,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x3a, 0x4d, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x1e, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xaf, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x42, 0x92, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x68, 0x74, 0x6d,
	0x6c, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x72, 0x65, 0x77, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x68, 0x74, 0x6d, 0x6c, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x2f, 0x76,
	0x31, 0x3b, 0x70, 0x68, 0x74, 0x6d, 0x6c, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa,
	0x02, 0x08, 0x50, 0x68, 0x74, 0x6d, 0x6c, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x08, 0x50, 0x68, 0x74,
	0x6d, 0x6c, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x50, 0x68, 0x74, 0x6d, 0x6c, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x50,
	0x68, 0x74, 0x6d, 0x6c, 0x3a, 0x3a, 0x56, 0x31,
}

var (
	file_phtml_v1_options_proto_rawDescOnce sync.Once
	file_phtml_v1_options_proto_rawDescData = file_phtml_v1_options_proto_rawDesc
)

func file_phtml_v1_options_proto_rawDescGZIP() []byte {
	file_phtml_v1_options_proto_rawDescOnce.Do(func() {
		file_phtml_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_phtml_v1_options_proto_rawDescData)
	})
	return file_phtml_v1_options_proto_rawDescData
}

var file_phtml_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_phtml_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_phtml_v1_options_proto_goTypes = []interface{}{
	(Source)(0),                         // 0: phtml.v1.Source
	(*TemplOptions)(nil),                // 1: phtml.v1.TemplOptions
	(*RouteOptions)(nil),                // 2: phtml.v1.RouteOptions
	(*ParamFieldOptions)(nil),           // 3: phtml.v1.ParamFieldOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
	(*descriptorpb.MethodOptions)(nil),  // 6: google.protobuf.MethodOptions
}
var file_phtml_v1_options_proto_depIdxs = []int32{
	0, // 0: phtml.v1.ParamFieldOptions.source:type_name -> phtml.v1.Source
	4, // 1: phtml.v1.param:extendee -> google.protobuf.FieldOptions
	5, // 2: phtml.v1.templ:extendee -> google.protobuf.MessageOptions
	6, // 3: phtml.v1.route:extendee -> google.protobuf.MethodOptions
	3, // 4: phtml.v1.param:type_name -> phtml.v1.ParamFieldOptions
	1, // 5: phtml.v1.templ:type_name -> phtml.v1.TemplOptions
	2, // 6: phtml.v1.route:type_name -> phtml.v1.RouteOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	4, // [4:7] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_phtml_v1_options_proto_init() }
func file_phtml_v1_options_proto_init() {
	if File_phtml_v1_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phtml_v1_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phtml_v1_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phtml_v1_options_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phtml_v1_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_phtml_v1_options_proto_goTypes,
		DependencyIndexes: file_phtml_v1_options_proto_depIdxs,
		EnumInfos:         file_phtml_v1_options_proto_enumTypes,
		MessageInfos:      file_phtml_v1_options_proto_msgTypes,
		ExtensionInfos:    file_phtml_v1_options_proto_extTypes,
	}.Build()
	File_phtml_v1_options_proto = out.File
	file_phtml_v1_options_proto_rawDesc = nil
	file_phtml_v1_options_proto_goTypes = nil
	file_phtml_v1_options_proto_depIdxs = nil
}
