name: Check
permissions:
  contents: read

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
      - uses: magefile/mage-action@v3
        with:
          install-only: true
      - run: mage -v dev:test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.0"
          cache: false
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
          args: --timeout 3m
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
